In [1]:
# Dependencies
import requests
import json
import pandas as pd
# from ratelimit import limits, sleep_and_retry
import time

# Retrieve Alpha Vantage key from config.py
from config import alpha_key

### Get 5 minute VIX data for the current day and store in a new df

In [3]:
# API call to Alphavantage to get VIX data

url = f"https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=VIX&interval=5min&apikey={alpha_key}"
response = requests.get(url).json()
print(response)

{'Meta Data': {'1. Information': 'Intraday (5min) open, high, low, close prices and volume', '2. Symbol': 'VIX', '3. Last Refreshed': '2019-04-12 16:00:00', '4. Interval': '5min', '5. Output Size': 'Compact', '6. Time Zone': 'US/Eastern'}, 'Time Series (5min)': {'2019-04-12 16:00:00': {'1. open': '12.0900', '2. high': '12.1000', '3. low': '12.0600', '4. close': '12.0600', '5. volume': '0'}, '2019-04-12 15:55:00': {'1. open': '12.0300', '2. high': '12.0900', '3. low': '12.0300', '4. close': '12.0900', '5. volume': '0'}, '2019-04-12 15:50:00': {'1. open': '12.0800', '2. high': '12.0900', '3. low': '12.0300', '4. close': '12.0300', '5. volume': '0'}, '2019-04-12 15:45:00': {'1. open': '12.0700', '2. high': '12.0900', '3. low': '12.0700', '4. close': '12.0800', '5. volume': '0'}, '2019-04-12 15:40:00': {'1. open': '12.0900', '2. high': '12.1200', '3. low': '12.0800', '4. close': '12.0900', '5. volume': '0'}, '2019-04-12 15:35:00': {'1. open': '12.1300', '2. high': '12.1400', '3. low': '12.0900', '4. close': '12.0900', '5. volume': '0'}, '2019-04-12 15:30:00': {'1. open': '12.2000', '2. high': '12.2000', '3. low': '12.1200', '4. close': '12.1300', '5. volume': '0'}, '2019-04-12 15:25:00': {'1. open': '12.1900', '2. high': '12.2100', '3. low': '12.1900', '4. close': '12.2000', '5. volume': '0'}, '2019-04-12 15:20:00': {'1. open': '12.1900', '2. high': '12.1900', '3. low': '12.1700', '4. close': '12.1800', '5. volume': '0'}, '2019-04-12 15:15:00': {'1. open': '12.2200', '2. high': '12.2200', '3. low': '12.1800', '4. close': '12.1800', '5. volume': '0'}, '2019-04-12 15:10:00': {'1. open': '12.2000', '2. high': '12.2200', '3. low': '12.2000', '4. close': '12.2200', '5. volume': '0'}, '2019-04-12 15:05:00': {'1. open': '12.2100', '2. high': '12.2200', '3. low': '12.2000', '4. close': '12.2000', '5. volume': '0'}, '2019-04-12 15:00:00': {'1. open': '12.2000', '2. high': '12.2200', '3. low': '12.2000', '4. close': '12.2100', '5. volume': '0'}, '2019-04-12 14:55:00': {'1. open': '12.1900', '2. high': '12.2000', '3. low': '12.1900', '4. close': '12.2000', '5. volume': '0'}, '2019-04-12 14:50:00': {'1. open': '12.1700', '2. high': '12.1900', '3. low': '12.1700', '4. close': '12.1900', '5. volume': '0'}, '2019-04-12 14:45:00': {'1. open': '12.1700', '2. high': '12.1700', '3. low': '12.1500', '4. close': '12.1600', '5. volume': '0'}, '2019-04-12 14:40:00': {'1. open': '12.1600', '2. high': '12.1800', '3. low': '12.1600', '4. close': '12.1700', '5. volume': '0'}, '2019-04-12 14:35:00': {'1. open': '12.1800', '2. high': '12.1800', '3. low': '12.1600', '4. close': '12.1600', '5. volume': '0'}, '2019-04-12 14:30:00': {'1. open': '12.1900', '2. high': '12.1900', '3. low': '12.1800', '4. close': '12.1800', '5. volume': '0'}, '2019-04-12 14:25:00': {'1. open': '12.2200', '2. high': '12.2200', '3. low': '12.1900', '4. close': '12.1900', '5. volume': '0'}, '2019-04-12 14:20:00': {'1. open': '12.2300', '2. high': '12.2400', '3. low': '12.2100', '4. close': '12.2200', '5. volume': '0'}, '2019-04-12 14:15:00': {'1. open': '12.2400', '2. high': '12.2400', '3. low': '12.2200', '4. close': '12.2300', '5. volume': '0'}, '2019-04-12 14:10:00': {'1. open': '12.2300', '2. high': '12.2300', '3. low': '12.2100', '4. close': '12.2300', '5. volume': '0'}, '2019-04-12 14:05:00': {'1. open': '12.2600', '2. high': '12.2700', '3. low': '12.2200', '4. close': '12.2300', '5. volume': '0'}, '2019-04-12 14:00:00': {'1. open': '12.2700', '2. high': '12.2700', '3. low': '12.2600', '4. close': '12.2600', '5. volume': '0'}, '2019-04-12 13:55:00': {'1. open': '12.2800', '2. high': '12.2900', '3. low': '12.2700', '4. close': '12.2700', '5. volume': '0'}, '2019-04-12 13:50:00': {'1. open': '12.3100', '2. high': '12.3100', '3. low': '12.2800', '4. close': '12.2800', '5. volume': '0'}, '2019-04-12 13:45:00': {'1. open': '12.3000', '2. high': '12.3200', '3. low': '12.3000', '4. close': '12.3100', '5. volume': '0'}, '2019-04-12 13:40:00': {'1. open': '12.2900', '2. high': '12.3000', '3. low': '12.2800', '4. close': '12.3000', '5. volume': '0'}, '2019-04-12 13:35:00': {'1. open': '12.2700', '2. high': '12.2900', '3. low': '12.2600', '4. close': '12.2900', '5. volume': '0'}, '2019-04-12 13:30:00': {'1. open': '12.2600', '2. high': '12.2700', '3. low': '12.2600', '4. close': '12.2700', '5. volume': '0'}, '2019-04-12 13:25:00': {'1. open': '12.2600', '2. high': '12.2700', '3. low': '12.2500', '4. close': '12.2600', '5. volume': '0'}, '2019-04-12 13:20:00': {'1. open': '12.2600', '2. high': '12.2700', '3. low': '12.2500', '4. close': '12.2600', '5. volume': '0'}, '2019-04-12 13:15:00': {'1. open': '12.2800', '2. high': '12.2800', '3. low': '12.2600', '4. close': '12.2600', '5. volume': '0'}, '2019-04-12 13:10:00': {'1. open': '12.2600', '2. high': '12.2800', '3. low': '12.2600', '4. close': '12.2800', '5. volume': '0'}, '2019-04-12 13:05:00': {'1. open': '12.3200', '2. high': '12.3200', '3. low': '12.2700', '4. close': '12.2700', '5. volume': '0'}, '2019-04-12 13:00:00': {'1. open': '12.3300', '2. high': '12.3400', '3. low': '12.3200', '4. close': '12.3200', '5. volume': '0'}, '2019-04-12 12:55:00': {'1. open': '12.3600', '2. high': '12.3600', '3. low': '12.3300', '4. close': '12.3400', '5. volume': '0'}, '2019-04-12 12:50:00': {'1. open': '12.3700', '2. high': '12.3800', '3. low': '12.3600', '4. close': '12.3600', '5. volume': '0'}, '2019-04-12 12:45:00': {'1. open': '12.4100', '2. high': '12.4100', '3. low': '12.3700', '4. close': '12.3700', '5. volume': '0'}, '2019-04-12 12:40:00': {'1. open': '12.4200', '2. high': '12.4400', '3. low': '12.4100', '4. close': '12.4100', '5. volume': '0'}, '2019-04-12 12:35:00': {'1. open': '12.4000', '2. high': '12.4200', '3. low': '12.4000', '4. close': '12.4200', '5. volume': '0'}, '2019-04-12 12:30:00': {'1. open': '12.3900', '2. high': '12.4100', '3. low': '12.3900', '4. close': '12.4000', '5. volume': '0'}, '2019-04-12 12:25:00': {'1. open': '12.3800', '2. high': '12.4000', '3. low': '12.3800', '4. close': '12.3900', '5. volume': '0'}, '2019-04-12 12:20:00': {'1. open': '12.3300', '2. high': '12.3700', '3. low': '12.3000', '4. close': '12.3700', '5. volume': '0'}, '2019-04-12 12:15:00': {'1. open': '12.3400', '2. high': '12.3500', '3. low': '12.3300', '4. close': '12.3300', '5. volume': '0'}, '2019-04-12 12:10:00': {'1. open': '12.3700', '2. high': '12.3800', '3. low': '12.3300', '4. close': '12.3500', '5. volume': '0'}, '2019-04-12 12:05:00': {'1. open': '12.4100', '2. high': '12.4100', '3. low': '12.3700', '4. close': '12.3700', '5. volume': '0'}, '2019-04-12 12:00:00': {'1. open': '12.4300', '2. high': '12.4300', '3. low': '12.4000', '4. close': '12.4100', '5. volume': '0'}, '2019-04-12 11:55:00': {'1. open': '12.4900', '2. high': '12.4900', '3. low': '12.4300', '4. close': '12.4300', '5. volume': '0'}, '2019-04-12 11:50:00': {'1. open': '12.5300', '2. high': '12.5500', '3. low': '12.4900', '4. close': '12.4900', '5. volume': '0'}, '2019-04-12 11:45:00': {'1. open': '12.5500', '2. high': '12.5800', '3. low': '12.5300', '4. close': '12.5300', '5. volume': '0'}, '2019-04-12 11:40:00': {'1. open': '12.5300', '2. high': '12.5400', '3. low': '12.5100', '4. close': '12.5400', '5. volume': '0'}, '2019-04-12 11:35:00': {'1. open': '12.5000', '2. high': '12.5400', '3. low': '12.5000', '4. close': '12.5400', '5. volume': '0'}, '2019-04-12 11:30:00': {'1. open': '12.5200', '2. high': '12.5200', '3. low': '12.4900', '4. close': '12.5000', '5. volume': '0'}, '2019-04-12 11:25:00': {'1. open': '12.5800', '2. high': '12.5900', '3. low': '12.5100', '4. close': '12.5100', '5. volume': '0'}, '2019-04-12 11:20:00': {'1. open': '12.5700', '2. high': '12.6400', '3. low': '12.5700', '4. close': '12.5800', '5. volume': '0'}, '2019-04-12 11:15:00': {'1. open': '12.5700', '2. high': '12.6300', '3. low': '12.5600', '4. close': '12.5600', '5. volume': '0'}, '2019-04-12 11:10:00': {'1. open': '12.5000', '2. high': '12.5700', '3. low': '12.5000', '4. close': '12.5600', '5. volume': '0'}, '2019-04-12 11:05:00': {'1. open': '12.4700', '2. high': '12.5100', '3. low': '12.4600', '4. close': '12.5000', '5. volume': '0'}, '2019-04-12 11:00:00': {'1. open': '12.4300', '2. high': '12.4700', '3. low': '12.4200', '4. close': '12.4700', '5. volume': '0'}, '2019-04-12 10:55:00': {'1. open': '12.4800', '2. high': '12.5200', '3. low': '12.4300', '4. close': '12.4400', '5. volume': '0'}, '2019-04-12 10:50:00': {'1. open': '12.4800', '2. high': '12.4900', '3. low': '12.4700', '4. close': '12.4800', '5. volume': '0'}, '2019-04-12 10:45:00': {'1. open': '12.3600', '2. high': '12.4800', '3. low': '12.3600', '4. close': '12.4800', '5. volume': '0'}, '2019-04-12 10:40:00': {'1. open': '12.3000', '2. high': '12.3600', '3. low': '12.3000', '4. close': '12.3600', '5. volume': '0'}, '2019-04-12 10:35:00': {'1. open': '12.2500', '2. high': '12.3000', '3. low': '12.2400', '4. close': '12.3000', '5. volume': '0'}, '2019-04-12 10:30:00': {'1. open': '12.2700', '2. high': '12.2700', '3. low': '12.2200', '4. close': '12.2500', '5. volume': '0'}, '2019-04-12 10:25:00': {'1. open': '12.2700', '2. high': '12.3200', '3. low': '12.2700', '4. close': '12.2800', '5. volume': '0'}, '2019-04-12 10:20:00': {'1. open': '12.2000', '2. high': '12.2600', '3. low': '12.1800', '4. close': '12.2600', '5. volume': '0'}, '2019-04-12 10:15:00': {'1. open': '12.1900', '2. high': '12.1900', '3. low': '12.1100', '4. close': '12.1900', '5. volume': '0'}, '2019-04-12 10:10:00': {'1. open': '12.2500', '2. high': '12.2500', '3. low': '12.1900', '4. close': '12.1900', '5. volume': '0'}, '2019-04-12 10:05:00': {'1. open': '12.2000', '2. high': '12.2500', '3. low': '12.1800', '4. close': '12.2500', '5. volume': '0'}, '2019-04-12 10:00:00': {'1. open': '12.2100', '2. high': '12.2200', '3. low': '12.1900', '4. close': '12.1900', '5. volume': '0'}, '2019-04-12 09:55:00': {'1. open': '12.3100', '2. high': '12.3100', '3. low': '12.1900', '4. close': '12.2100', '5. volume': '0'}, '2019-04-12 09:50:00': {'1. open': '12.3100', '2. high': '12.3100', '3. low': '12.2700', '4. close': '12.3000', '5. volume': '0'}, '2019-04-12 09:45:00': {'1. open': '12.3100', '2. high': '12.3100', '3. low': '12.2800', '4. close': '12.3000', '5. volume': '0'}, '2019-04-12 09:40:00': {'1. open': '12.5700', '2. high': '12.5700', '3. low': '12.3300', '4. close': '12.3300', '5. volume': '0'}, '2019-04-12 09:35:00': {'1. open': '12.5700', '2. high': '12.5800', '3. low': '12.5400', '4. close': '12.5800', '5. volume': '0'}, '2019-04-11 16:00:00': {'1. open': '13.0600', '2. high': '13.0900', '3. low': '13.0500', '4. close': '13.0900', '5. volume': '0'}, '2019-04-11 15:55:00': {'1. open': '13.2000', '2. high': '13.2000', '3. low': '13.0600', '4. close': '13.0700', '5. volume': '0'}, '2019-04-11 15:50:00': {'1. open': '13.1700', '2. high': '13.1900', '3. low': '13.1500', '4. close': '13.1900', '5. volume': '0'}, '2019-04-11 15:45:00': {'1. open': '13.1900', '2. high': '13.2100', '3. low': '13.1700', '4. close': '13.1700', '5. volume': '0'}, '2019-04-11 15:40:00': {'1. open': '13.1700', '2. high': '13.2100', '3. low': '13.1700', '4. close': '13.2100', '5. volume': '0'}, '2019-04-11 15:35:00': {'1. open': '13.2600', '2. high': '13.2600', '3. low': '13.1600', '4. close': '13.1800', '5. volume': '0'}, '2019-04-11 15:30:00': {'1. open': '13.2500', '2. high': '13.2700', '3. low': '13.2500', '4. close': '13.2700', '5. volume': '0'}, '2019-04-11 15:25:00': {'1. open': '13.2200', '2. high': '13.2500', '3. low': '13.2100', '4. close': '13.2500', '5. volume': '0'}, '2019-04-11 15:20:00': {'1. open': '13.2600', '2. high': '13.2600', '3. low': '13.2100', '4. close': '13.2200', '5. volume': '0'}, '2019-04-11 15:15:00': {'1. open': '13.2300', '2. high': '13.2700', '3. low': '13.2200', '4. close': '13.2600', '5. volume': '0'}, '2019-04-11 15:10:00': {'1. open': '13.2400', '2. high': '13.2400', '3. low': '13.2100', '4. close': '13.2300', '5. volume': '0'}, '2019-04-11 15:05:00': {'1. open': '13.3300', '2. high': '13.3300', '3. low': '13.2400', '4. close': '13.2400', '5. volume': '0'}, '2019-04-11 15:00:00': {'1. open': '13.3400', '2. high': '13.3700', '3. low': '13.3200', '4. close': '13.3300', '5. volume': '0'}, '2019-04-11 14:55:00': {'1. open': '13.3000', '2. high': '13.3500', '3. low': '13.3000', '4. close': '13.3400', '5. volume': '0'}, '2019-04-11 14:50:00': {'1. open': '13.2800', '2. high': '13.3000', '3. low': '13.2800', '4. close': '13.2900', '5. volume': '0'}, '2019-04-11 14:45:00': {'1. open': '13.3700', '2. high': '13.3700', '3. low': '13.2700', '4. close': '13.2800', '5. volume': '0'}, '2019-04-11 14:40:00': {'1. open': '13.3700', '2. high': '13.3800', '3. low': '13.3600', '4. close': '13.3700', '5. volume': '0'}, '2019-04-11 14:35:00': {'1. open': '13.3900', '2. high': '13.3900', '3. low': '13.3400', '4. close': '13.3600', '5. volume': '0'}, '2019-04-11 14:30:00': {'1. open': '13.3300', '2. high': '13.3800', '3. low': '13.3300', '4. close': '13.3800', '5. volume': '0'}, '2019-04-11 14:25:00': {'1. open': '13.3300', '2. high': '13.3400', '3. low': '13.3200', '4. close': '13.3300', '5. volume': '0'}, '2019-04-11 14:20:00': {'1. open': '13.3100', '2. high': '13.3400', '3. low': '13.3000', '4. close': '13.3200', '5. volume': '0'}, '2019-04-11 14:15:00': {'1. open': '13.2700', '2. high': '13.3100', '3. low': '13.2700', '4. close': '13.2900', '5. volume': '0'}}}

In [4]:
data_items = response['Time Series (5min)']
vix_df = pd.DataFrame.from_dict(data_items, orient='index')
vix_df.head()

                     1. open  2. high   3. low 4. close 5. volume
2019-04-11 14:15:00  13.2700  13.3100  13.2700  13.2900         0
2019-04-11 14:20:00  13.3100  13.3400  13.3000  13.3200         0
2019-04-11 14:25:00  13.3300  13.3400  13.3200  13.3300         0
2019-04-11 14:30:00  13.3300  13.3800  13.3300  13.3800         0
2019-04-11 14:35:00  13.3900  13.3900  13.3400  13.3600         0

In [5]:
# Drop volume column and rename the column headers
clean_vix_df = vix_df.drop(['5. volume'], axis=1)
clean_vix_df.head()

                     1. open  2. high   3. low 4. close
2019-04-11 14:15:00  13.2700  13.3100  13.2700  13.2900
2019-04-11 14:20:00  13.3100  13.3400  13.3000  13.3200
2019-04-11 14:25:00  13.3300  13.3400  13.3200  13.3300
2019-04-11 14:30:00  13.3300  13.3800  13.3300  13.3800
2019-04-11 14:35:00  13.3900  13.3900  13.3400  13.3600

In [6]:
clean_vix_df.columns = ['open', 'high','low','close']
clean_vix_df.head()

                        open     high      low    close
2019-04-11 14:15:00  13.2700  13.3100  13.2700  13.2900
2019-04-11 14:20:00  13.3100  13.3400  13.3000  13.3200
2019-04-11 14:25:00  13.3300  13.3400  13.3200  13.3300
2019-04-11 14:30:00  13.3300  13.3800  13.3300  13.3800
2019-04-11 14:35:00  13.3900  13.3900  13.3400  13.3600

In [7]:
### Export to csv
clean_vix_df.to_csv("vix_intraday.csv", index=True, header=True)